### ISSUE TITLE
invertire la nav dell'archivio

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/hildegard#95]
attualmente è così

```yaml
  - Archivio:
      - '2024':
          - archivio/2 giugno 2024.md
          - archivio/9 giugno 2024.md
          - ...
          - archivio/29 dicembre 2024.md
      - '2025':
          - archivio/12 gennaio 2025.md
          - ...
          - archivio/6 aprile 2025.md
  - News: news/index.md
  ```

questo vuol dire che quando faccio click sulla sezione "Archivio" vengo dirottato in `archivio/2 giugno 2024.md`. Invece avrebbe più senso essere dirottati all'ultimo `archivio/6 aprile 2025.md'.

Per fare sta cosa si potrebbe invertire l'ordine degli elementi della nav:

```yaml
  - Archivio:
      - '2025':
          - archivio/12 gennaio 2025.md
          - ...
          - archivio/6 aprile 2025.md
      - '2024':
          - archivio/2 giugno 2024.md
          - archivio/9 giugno 2024.md
          - ...
          - archivio/29 dicembre 2024.md
  - News: news/index.md
  ```

Bisognerebbe modificare la **terribile** funzione `add_element_to_mkdocs_nav`
